name_experiment: grav_ddpm_cond
seed: 1234
mode: fit

datamodule:
  path_surfaces_h5py: null
  path_observations_h5py: null
  batch_size: 64
  shuffle_data: True
  num_workers: 4
  pct_train: 0.9
  pct_val: 0.08
  pct_test: 0.02
  two_dimensional: True
  gravity_data:
    train_path: data/gravity_data/training_data.hdf5
    val_path: data/gravity_data/validation_data.hdf5
    test_path: data/gravity_data/testing_data.hdf5      

lit_model_type: LitDDPMGrav
lit_model:
  diffusion: Diffusion2d
  conf_diffusion:                       
    noise_steps: 500
    beta_start: 0.0001
    beta_end: 0.02
    surf_size: 32
  ddpm: UNet_conditional2d
  conf_ddpm:
    c_in: 2
    c_out: 1
    time_dim: 256
    small: True
  ema: EMA2d
  conf_ema:
    beta: 0.995
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [1, 1, 32, 32]
  batch_size: 100
  cfg_scale: 0
  n_sample_for_metric: 100

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: false
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10

tensorboard_logs:
  save_dir: logs_gravity

checkpoint_callback:
  monitor: val/loss
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null