name_experiment: tests_ddpm_all_seq
seed: 1234
mode: fit

datamodule:
  path_data_json: data/spillpoint_train.json
  # path_surfaces_h5py: data/surfaces64.hdf5
  # path_observations_h5py: data/observations64.hdf5
  batch_size: 32
  shuffle_data: True
  num_workers: 4
  pct_train: 0.95
  pct_val: 0.05
  pct_test: 0
  two_dimensional: False
  sequential_cond: True
  sequential_surfaces: True
  random_subsequence: False
  pad_all: True
  use_collate_fn: False

lit_model_type: LitDDPM1dFull
lit_model:
  diffusion: DiffusionTransformer2
  conf_diffusion:
    noise_steps: 2
    beta_start: 0.0001
    beta_end: 0.02
    surf_size: 32
  ddpm: UNet_conditional
  conf_ddpm:
    c_in: 13
    c_out: 5
    time_dim: 256
    personal: True
  ema: EMA
  conf_ema:
    beta: 0.995
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  latent_dim: 20
  validation_x_shape: [3, 1, 64]
  use_rd_y: False
  batch_size: 100
  cfg_scale: 0
  n_sample_for_metric: 100
  sequential_cond: False

trainer:
  auto_lr_find: False                     
  min_epochs: 1                             
  max_epochs: 50                        
  fast_dev_run: false                   
  accelerator: gpu
  devices: [1]
  log_every_n_steps: 10                 

tensorboard_logs:
  save_dir: logs                          
#   name: test_res_inject

checkpoint_callback:                
  monitor: val/loss                     
  mode: min                               
  save_last: True                     
  filename: best-checkpoint                  

checkpoint_path: null