name_experiment: seq2seq_cond_comp/src_dim256_heads4_enc2_dec2_dimff1024_timedim256
seed: 1234
mode: fit

datamodule:
  path_data_json: data/spillpoint_train.json
  # path_surfaces_h5py: data/surfaces64.hdf5
  # path_observations_h5py: data/observations64.hdf5
  batch_size: 128
  shuffle_data: True
  num_workers: 4
  pct_train: 0.95
  pct_val: 0.05
  pct_test: 0
  two_dimensional: False
  sequential_cond: True
  sequential_surfaces: True
  use_collate_fn: True

lit_model_type: LitDDPM1dSeq2Seq2
lit_model:
  diffusion: DiffusionTransformer
  conf_diffusion:
    noise_steps: 500
    beta_start: 0.0001
    beta_end: 0.02
    surf_size: 32
  ddpm: Transformer4Diffusion
  conf_ddpm:
    in_channels: 8
    out_channels: 5
    resolution: 32
    dim_model: 256
    num_heads: 4
    num_encoder_layers: 2
    num_decoder_layers: 2
    dropout: 0.1
    dim_feed_forward: 1024
    time_dim: 256
    conditional: True
    max_len: 500
    causal_decoder: False
  ema: EMA
  conf_ema:
    beta: 0.995
  lr: 0.0002
  b1: 0.9
  b2: 0.95
  latent_dim: 20
  validation_x_shape: [1, 1, 64]
  use_rd_y: False
  batch_size: 100
  cfg_scale: 0
  n_sample_for_metric: 100
  sequential_cond: True

trainer:
  auto_lr_find: False                     
  min_epochs: 1                             
  max_epochs: 50
  fast_dev_run: false                   
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10                 

tensorboard_logs:
  save_dir: logs                          
#   name: test_res_inject

checkpoint_callback:                
  monitor: val/loss                     
  mode: min                               
  save_last: True                     
  filename: best-checkpoint

tune_callback:
  metrics:
    loss: val/loss
  on: validation_end 

checkpoint_path: null