name_experiment: inject_6_larger
seed: 1234

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModels.jl/surfaces64.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModels.jl/observations64.hdf5
  batch_size: 512
  shuffle: False
  num_workers: 4
  pct_train: 0.8
  pct_val: 0.2
  pct_test: 0.0

lit_model_type: LitDCGAN
lit_model:
  generator: LargeGeneratorInject #InjectionGenerator
  discriminator: LargerDiscriminator #InjectionDiscriminator
  conf_generator:
    latent_dim: 20
    layers: [
      {Cv: [128, 128, 4, 2, 1], BN: [128], LR: null},
      {CvT: [128, 256, 4, 2, 1], BN: [256], LR: null, D: [0.25,]},
      {CvT: [256, 512, 4, 2, 1], BN: [512], LR: null},
      {Cv: [512, 256, 4, 2, 1], LR: null},
      {Cv: [256, 128, 3, 1, 1], LR: null},
      {Cv: [128, 128, 3, 1, 1], LR: null},
      {Cv: [128, 1, 3, 1, 1]},
    ]
    injections: [
      [True, 0, 1],
      [True, 2, 0.5],
      [True, 2, 1],
      [True, 2, 2],
      [True, 0, 1],
      [True, 2, 1],
      [True, 2, 1],
    ]
  conf_discriminator:
    layers: [
      {Cv: [3, 128, 3, 2, 1]},
      {LR: [0.2], D: [0.4]},
      {Cv: [128, 256, 3, 2, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv: [256, 256, 3, 2, 1]},
      {D: [0.4]},
      {F: null},
      {L: [2048, 1]},
    ]
    spectral_norm: [
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
    ]
  g_lr: 0.0002
  d_lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [1, 1, 64]
  use_rd_y: True
  batch_size: 512
  wasserstein_gp_loss: False

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: False
  log_every_n_steps: 10
  accelerator: gpu
  devices: [3]
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback:
  monitor: val/L2Metric
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null