name_experiment: cvae_test
seed: 1234

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/DeepGenerativeModels.jl/surfaces64.hdf5
  path_observations_h5py: /home/abigeard/DeepGenerativeModels.jl/observations64.hdf5
  batch_size: 512
  shuffle_data: True
  num_workers: 4
  pct_train: 0.8
  pct_val: 0.2
  pct_test: 0

lit_model_type: LitVAE
lit_model:
  vae: VAE #InjectionGenerator
  conf_vae:
    latent_dim: 18
    encoder_model: Encoder
    conf_encoder:
      hot_one_encoding: True
    decoder_model: Decoder
    conf_decoder:
      hot_one_encoding: False
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [10, 1, 64]
  use_rd_y: False
  batch_size: 512

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 40
  fast_dev_run: False
  accelerator: gpu
  devices: [3]
  log_every_n_steps: 10
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback:
  monitor: val/L2Metric
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null