name_experiment: seq_ddpm_test_metrics
seed: 1234
mode: fit

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/surfaces_multipleobs.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/observations_multipleobs.hdf5
  batch_size: 512
  shuffle: False
  num_workers: 4
  pct_train: 0.8
  pct_val: 0.19
  pct_test: 0.01
  sequential_cond: True

lit_model_type: LitDDPM
lit_model:
  diffusion: Diffusion
  conf_diffusion:
    noise_steps: 500
    beta_start: 0.0001
    beta_end: 0.02
    surf_size: 64
  ddpm: UNet_conditional
  conf_ddpm:
    c_in: 3
    c_out: 1
    time_dim: 256
  ema: EMA
  conf_ema:
    beta: 0.995
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  latent_dim: 20
  validation_x_shape: [1, 1, 64]
  use_rd_y: False
  batch_size: 512
  cfg_scale: 0
  sequential_cond: True
  encoding_layer: ConditionEncoding
  conf_encoding_layer:
    input_size: 128
    hidden_size: 128
    num_layers: 1
    batch_first: True

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 80
  fast_dev_run: False
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback:
  monitor: val/L2Metric
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: logs/seq_ddpm/version_9/checkpoints/epoch=79-step=12560.ckpt