name_experiment: test

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: data/surfaces64.hdf5
  path_observations_h5py: data/observations64.hdf5
  batch_size: 128
  shuffle: True
  num_workers: 4
  pct_train: 0.8
  pct_val: 0.2
  pct_test: 0

lit_model_type: LitDCGAN
lit_model:
  generator: SmallGenerator #InjectionGenerator
  discriminator: SmallDiscriminator #InjectionDiscriminator
  conf_generator:
    latent_dim: 100
  conf_discriminator: {}
  g_lr: 0.002
  d_lr: 0.002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [5, 1, 51]
  use_rd_y: True

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 20
  fast_dev_run: False
  gpus: [0]
  log_every_n_steps: 10
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: first_run

checkpoint_callback:
  monitor: val/loss
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null