name_experiment: small_wgp_latent20
seed: 1234

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModels.jl/surfaces64.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModels.jl/observations64.hdf5
  batch_size: 256
  shuffle: False
  num_workers: 4
  pct_train: 0.8
  pct_val: 0.1999
  pct_test: 0.0001

lit_model_type: LitDCGAN
lit_model:
  generator: SmallGenerator #InjectionGenerator
  discriminator: SmallDiscriminator #InjectionDiscriminator
  conf_generator:
    latent_dim: 20
  conf_discriminator: {}
  g_lr: 0.0002
  d_lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [10, 1, 64]
  use_rd_y: True
  batch_size: 256
  wasserstein_gp_loss: True

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: False
  gpus: [2]
  log_every_n_steps: 10
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback:
  monitor: val/L2Metric
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null