name_experiment: cvae_ore
seed: 1234                                   
mode: fit                                    

datamodule:
  path_surfaces_h5py: data/ore_maps_32.hdf5
  path_observations_h5py: data/ore_maps_observations_32.hdf5
  batch_size: 64                      
  shuffle_data: True                         
  num_workers: 4                             
  pct_train: 0.9                             
  pct_val: 0.08                              
  pct_test: 0.02                             
  two_dimensional: True             

lit_model_type: LitModelVAEOre
lit_model:
  latent_dim: 256
  lr: 0.0001             
  batch_size: 100                            
  n_sample_for_metric: 100
  conditional: True
  validation_x_shape: [10, 1, 32, 32]            

trainer:
  auto_lr_find: False                        
  min_epochs: 1                              
  max_epochs: 50                             
  fast_dev_run: false                        
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10                      

tensorboard_logs:
  save_dir: logs_ore                           

checkpoint_callback:                         
  mode: min                                  
  save_last: True                            
  filename: best-checkpoint                  

checkpoint_path: null      