name_experiment: ore_maps_ddpm_200
seed: 1234
mode: fit

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_32.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_observations_32.hdf5
  batch_size: 100
  shuffle: False
  num_workers: 4
  pct_train: 0.9
  pct_val: 0.08
  pct_test: 0.02
  sequential_cond: False
  two_dimensional: True

lit_model_type: LitDDPM2d
lit_model:
  diffusion: Diffusion2d
  conf_diffusion:
    noise_steps: 200
    beta_start: 0.0001
    beta_end: 0.02
    surf_size: 32
  ddpm: UNet_conditional2d
  conf_ddpm:
    c_in: 3
    c_out: 1
    time_dim: 256
  ema: EMA2d
  conf_ema:
    beta: 0.995
  lr: 0.0002
  b1: 0.5
  b2: 0.999
  latent_dim: 20
  validation_x_shape: [1, 1, 32, 32]
  use_rd_y: True
  batch_size: 100
  cfg_scale: 0
  n_sample_for_metric: 100

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: False
  accelerator: gpu
  devices: [1]
  log_every_n_steps: 10

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback:
  monitor: val/loss
  mode: min
  save_last: True
  filename: best-checkpoint

checkpoint_path: null