name_experiment: usual_gan_nolinear_latent
seed: 1234
mode: fit

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_32.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_observations_32.hdf5
  batch_size: 128
  shuffle_data: True
  num_workers: 4
  pct_train: 0.9
  pct_val: 0.08
  pct_test: 0.02
  sequential_cond: False
  two_dimensional: True

lit_model_type: LitDCGAN2d
lit_model:
  generator: LargeGeneratorInject2d
  discriminator: LargerDiscriminator2d
  conf_generator:
    latent_dim: 32
    layers: [
      {Cv2d: [128, 128, [4,4], [2,2], [1,1]], BN2d: [128], LR: null, UpSample: [null, 2, bilinear]},
      {Cv2d: [128, 256, [3,3], [1,1], [1,1]], BN2d: [256], LR: null, D: [0.25,], UpSample: [null, 2, bilinear]},
      {Cv2d: [256, 512, [4,4], [2,2], [1,1]], BN2d: [512], LR: null},
      {Cv2d: [512, 512, [3,3], [1,1], [1,1]], LR: null},
      {Cv2d: [512, 256, [3,3], [1,1], [1,1]], LR: null},
      {Cv2d: [256, 256, [3,3], [1,1], [1,1]], LR: null},
      {Cv2d: [256, 128, [3,3], [1,1], [1,1]], LR: null},
      {Cv2d: [128, 1, [3,3], [1,1], [1,1]]},
    ]
    injections: [
      [False, 0, 1],
      [False, 0, 1],
      [False, 0, 2],
      [False, 0, 1],
      [False, 0, 1],
      [False, 0, 1],
      [False, 0, 1],
      [False, 0, 1],
    ]
  conf_discriminator:
    layers: [
      {Cv2d: [1, 128, 3, 2, 1]},
      {LR: [0.2], D: [0.4]},
      {Cv2d: [128, 256, 3, 2, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv2d: [256, 256, 3, 1, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv2d: [256, 128, 3, 1, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv2d: [128, 128, 3, 1, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv2d: [128, 64, 3, 1, 1]},
      {LR: [0.2], D: [0.4], LR: [0.2]},
      {Cv2d: [64, 32, 3, 1, 1]},
      {D: [0.4]},
      {F: null},
      {L: [2048, 1]},
    ]
    spectral_norm: [
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
      False,
    ]
    no_inject: True
  g_lr: 0.0002
  d_lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [10, 1, 32, 32]
  use_rd_y: True
  batch_size: 150
  wasserstein_gp_loss: w
  n_sample_for_metric: 100
  latent_1d: False

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: False
  log_every_n_steps: 10
  accelerator: gpu
  devices: [0]
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs/gans_inject
  name: test_res_inject

checkpoint_callback: {}
  # monitor: val/L2Metric
  # mode: min
  # save_last: True
  # filename: best-checkpoint

checkpoint_path: null