name_experiment: stylegan_ore_maps
seed: 1234
mode: fit

datamodule:
  # name: MyDataModule
  path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_32.hdf5
  path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_observations_32.hdf5
  batch_size: 128
  shuffle: False
  num_workers: 4
  pct_train: 0.9
  pct_val: 0.08
  pct_test: 0.02
  sequential_cond: False
  two_dimensional: True

lit_model_type: LitDCGAN2d
lit_model:
  generator: Generator
  discriminator: Discriminator
  conf_generator:
    z_dim: 32
    c_dim: 32
    w_dim: 32
    img_resolution: 32
    img_channels: 1
    latent_dim: 32
  conf_discriminator:
    c_dim: 3
    img_resolution: 32
    img_channels: 1
  g_lr: 0.0002
  d_lr: 0.0002
  b1: 0.5
  b2: 0.999
  validation_x_shape: [10, 1, 32, 32]
  use_rd_y: True
  batch_size: 150
  wasserstein_gp_loss: w
  n_sample_for_metric: 100
  latent_1d: False

trainer:
  auto_lr_find: False
  min_epochs: 1
  max_epochs: 50
  fast_dev_run: False
  log_every_n_steps: 10
  accelerator: gpu
  devices: [0]
  # flush_logs_every_n_steps: 10
  # learning_rate: 0.0001

tensorboard_logs:
  save_dir: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/logs
  name: test_res_inject

checkpoint_callback: {}
  # monitor: val/L2Metric
  # mode: min
  # save_last: True
  # filename: best-checkpoint

checkpoint_path: null