name_experiment: stable_diff_oremaps
seed: 1234
mode: fit

datamodule:
  # path_data_json: data/spillpoint_train.json
  path_surfaces_h5py: data/ore_maps_32.hdf5
  path_observations_h5py: data/ore_maps_observations_32.hdf5
  batch_size: 32
  shuffle_data: True
  num_workers: 4
  pct_train: 0.95
  pct_val: 0.05
  pct_test: 0
  two_dimensional: True
  sequential_cond: True
  sequential_surfaces: False
  random_subsequence: False
  pad_all: False
  use_collate_fn: True
  dict_output: True

lit_model_type: LatentDiffusion2d
learning_rate: 0.001
lit_model:
  linear_start: 0.00085
  linear_end: 0.012
  num_timesteps_cond: 1
  log_every_t: 200
  timesteps: 1000
  first_stage_key: surfaces
  cond_stage_key: observations
  image_size: 32
  channels: 4
  cond_stage_trainable: true
  conditioning_key: crossattn
  monitor: val/loss_simple_ema
  scale_factor: 0.18215
  use_ema: False
  validation_x_shape: [3, 1, 32]

  unet_config:
    target: stable_diffusion_2d.ldm.modules.diffusionmodules.openaimodel.UNetModel2d
    params:
      dims: 1
      image_size: 32
      in_channels: 3
      out_channels: 1
      model_channels: 32
      attention_resolutions:
      - 4
      - 2
      - 1
      num_res_blocks: 2
      channel_mult:
      - 1
      - 2
      - 4
      - 4
      num_heads: 2
      use_spatial_transformer: true
      transformer_depth: 1
      context_dim: 32
      use_checkpoint: true
      legacy: False

  # first_stage_config:
  #   target: ldm.models.autoencoder.AutoencoderKL
  #   params:
  #     embed_dim: 4
  #     monitor: val/rec_loss
  #     ddconfig:
  #       double_z: true
  #       z_channels: 4
  #       resolution: 256
  #       in_channels: 3
  #       out_ch: 3
  #       ch: 128
  #       ch_mult:
  #       - 1
  #       - 2
  #       - 4
  #       - 4
  #       num_res_blocks: 2
  #       attn_resolutions: []
  #       dropout: 0.0
  #     lossconfig:
  #       target: torch.nn.Identity

  # cond_stage_config:
  #   target: ldm.modules.encoders.modules.BERTEmbedder
  #   params:
  #     n_embed: 128
  #     n_layer: 4
  cond_stage_config:
    target: stable_diffusion_2d.ldm.modules.encoders.modules.IdentityEncoding
    params: {}

trainer:
  auto_lr_find: False                     
  min_epochs: 1                             
  max_epochs: 50                        
  fast_dev_run: false                   
  accelerator: gpu
  devices: [0]
  log_every_n_steps: 10                 

tensorboard_logs:
  save_dir: logs                          
#   name: test_res_inject

checkpoint_callback:                
  monitor: val/loss                     
  mode: min                               
  save_last: True                     
  filename: best-checkpoint                  

checkpoint_path: null