path_logs: logs/ore_maps_ddpm_1000/version_0

update_conf:
  mode: test

  datamodule: 
    path_surfaces_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_32.hdf5
    path_observations_h5py: /home/abigeard/RA_CCS/DeepGenerativeModelsCCS/data/ore_maps_observations_32.hdf5
    batch_size: 3
    pct_train: 0.9
    pct_val: 0.08
    pct_test: 0.001

  trainer:
    devices: [3]