# path to the logs of a previous fitting experiment
# the corresponding configuration and checkpoint will be taken from this folder
path_logs: logs/ddpms/ddpm_ore_maps_100/version_0

# what is in update is similar to the configurations to run experiment
# just add what you want to overwrite in the configuration file in path_logs that will be used
# (for instance change batch size and datasets)
update_conf:
  mode: test

  datamodule: 
    path_surfaces_h5py: data/ore_maps_test_32.hdf5
    path_observations_h5py: data/ore_maps_test_obs_32.hdf5
    batch_size: 1
    pct_train: 0
    pct_val: 0
    pct_test: 0.5
    shuffle_data: False

  lit_model:
    n_sample_for_metric: 100

  trainer:
    devices: [0]