trial_type: DGM
name: DDPM500
savefolder: planning/results
Ntrials: 100
DGM_path: /home/acorso/Workspace/DeepGenerativeModelsCCS

model_config: planning/models/ddpm_ore_maps_500.yaml
model_ckpt: planning/models/ddpm500.ckpt

tree_queries: 1000
exploration_constant: 100.0
k_action: 2.0
alpha_action: 0.25
