trial_type: DGM_VOI
name: DDPM250_VOI
savefolder: planning/results
Ntrials: 10
DGM_path: /home/acorso/Workspace/DeepGenerativeModelsCCS

model_config: planning/models/ddpm_ore_maps_250.yaml
model_ckpt: planning/models/ddpm250.ckpt

Nsamples_VOI: 10
