trial_type: DGM_VOI_Multi
name: DDPM250_VOI_Multi
savefolder: planning/results
Ntrials: 50
DGM_path: /home/acorso/Workspace/DeepGenerativeModelsCCS

model_config: planning/models/ddpm_ore_maps_250.yaml
model_ckpt: planning/models/ddpm250.ckpt

Nobs_VOI: 50
Nsamples_est_VOI: 10
N_mc_actions_VOI: 50
