trial_type: DGM_VOI_Multi
name: GAN_HALF_2_32_W
savefolder: planning/results
Ntrials: 50
DGM_path: /home/acorso/Workspace/DeepGenerativeModelsCCS

model_config: planning/models/gan_halfinject_conv2_latent32_w/gan_halfinject_conv2_latent32_w.yaml
model_ckpt: planning/models/gan_halfinject_conv2_latent32_w/gan_halfinject_conv2_latent32_w.ckpt


Nobs_VOI: 50
Nsamples_est_VOI: 10
N_mc_actions_VOI: 50
