trial_type: DGM_VOI_Multi
name: GAN_ALL_2_128_W
savefolder: planning/results
Ntrials: 50
DGM_path: /home/acorso/Workspace/DeepGenerativeModelsCCS

model_config: planning/models/gan_fullinject_conv2_latent128_w/gan_fullinject_conv2_latent128_w.yaml
model_ckpt: planning/models/gan_fullinject_conv2_latent128_w/gan_fullinject_conv2_latent128_w.ckpt


Nobs_VOI: 50
Nsamples_est_VOI: 10
N_mc_actions_VOI: 50
