trial_type: GP_tree_search
name: GP_Tree_SqExp-M32
savefolder: planning/results
model_config: "gp_sqexp_m32_1500_b.jld2"

Ntrials: 50
tree_queries: 1500
exploration_constant: 0.5
k_action: 2.5
alpha_action: 0.3
k_state: 2.0
alpha_state: 0.5
depth: 30

init_drill_threshold: 5