trial_type: GP_VOI_Multi
name: GP_VOI_Multi_SqExp-M52
savefolder: planning/results
model_config: "gp_sqexp_m32_1500_b.jld2"
Ntrials: 50
Nobs_VOI: 50
Nsamples_est_VOI: 10
N_mc_actions_VOI: 50

init_drill_threshold: 5