trial_type: pomcpow
name: POMCPOW
savefolder: planning/results
Ntrials: 100
Nparticles: 10000

tree_queries: 1000
exploration_constant: 100.0
k_action: 2.0
alpha_action: 0.25
k_observation: 2.0
alpha_observation: 0.1